# Generated by Django 5.2.1 on 2025-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название заголовка",
                        max_length=50,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Заполните описание поста",
                        null=True,
                        verbose_name="Содержимое поста",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью",
                        null=True,
                        upload_to="product/img/",
                        verbose_name="Изображение",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("publication_sign", models.BooleanField(default=False)),
                (
                    "number_of_views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Счётчик просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новый пост",
                "verbose_name_plural": "Новые посты",
                "ordering": [
                    "title",
                    "content",
                    "preview",
                    "creation_date",
                    "number_of_views",
                ],
            },
        ),
    ]
