# Generated by Django 5.2.1 on 2025-06-27 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="postinfo",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.blogpost",
                verbose_name="Заголовок",
            ),
        ),
    ]
