# Generated by Django 4.2.2 on 2025-07-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="breed",
        ),
    ]
