# Generated by Django 4.2.2 on 2025-07-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_breed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price", "date_now", "updated_at"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_delete_product", "Can delete product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
