# Generated by Django 4.2.2 on 2025-07-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="choices",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="unpublish",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
