# Generated by Django 4.2.2 on 2025-07-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_choices_product_unpublish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="choices",
        ),
        migrations.AlterField(
            model_name="product",
            name="unpublish",
            field=models.BooleanField(default=False),
        ),
    ]
